# Python beginners course - Level 1 - NumPy
(inspired by work by Numan Yilmaz and exercises by Nicolas P. Rougier)

This tutorial consists of the following parts:

 - What is NumPy?
 - How to create NumPy arrays
 - Indexing, Fancy Indexing
 - Slicing
 - Universal Functions (Ufuncs)
 - Broadcasting
 - Masking, Sorting and Comparison

# 1. What is NumPy? 
NumPy is the foundation of data science in Python and is part of virtually every data science package. What makes NumPy such an incredible package is its data type 'ndarray'. ndarray stands for n-dimensional array and basically resembles a list. However, it is a lot faster than a regular Python list. A Python list can contain different kinds of data types, such as integers, strings, Boolean, True, False and even lists. On the other hand, NumPy arrays can hold only one type of data, and therefore doesn't have to check the type of data type for every single element of the array when it is doing the computations. This feature makes NumPy a great tool for data science research and projects. In between there will be exercises that will either give you a hint or part of the solution. If you are really lost or want to check your answer: find your answer [here](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md).

Before we get started, let's check the version of NumPy and Python.

In [72]:
# import numpy
import numpy as np

# sys was imported to check the python version
import sys 

# check the version of python and numpy
print('NumPy version:', np.__version__)
print('Python version',sys.version)

NumPy version: 1.17.3
Python version 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]


## 2. How to create NumPy arrays

There are many ways to create arrays in NumPy. We will take a look at a few of them here.

In [73]:
# create one dimensional numpy array
np.array([1, 2, 3])

array([1, 2, 3])

In [74]:
# Array of zeros
np.zeros(3)

array([0., 0., 0.])

In [75]:
# Array of 1s
np.ones(3)

array([1., 1., 1.])

In [76]:
# array of 3 random integers between 1 and 10
np.random.randint(1, 10, 3)

array([7, 5, 6])

In [77]:
# create evenly spaced array from 0 to 10 with steps of 2.5. 
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [78]:
# create 2-Dimensional array
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
# create 3x4 array values between 0 and 1
np.random.random((3,4))

array([[0.46863307, 0.88177499, 0.22458294, 0.80307824],
       [0.56308147, 0.70935826, 0.29011695, 0.70855975],
       [0.52465266, 0.41618662, 0.58249041, 0.26992052]])

### Exercise: Create an array of zeroes of size 10
(**hint**: np.zeros)

In [80]:
np.zeros(10)



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Exercise:  Create a null vector of size 10 but the fifth value which is 1
(**hint**: np.zeros and array\[4\])

In [81]:
null_vect = np.zeros(10)
null_vect[4] = 1
print(null_vect)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 3. Slightly more advanced tricks

Now that we know how to create arrays, lets see what we can do with them. 

First we create a 1-dimensional array 'a' and a 2-dimensional array 'b':

In [82]:
# create 1D and 2D arrays a and b
a = np.array([1,2,3])
b = np.random.randint(0,10, (3,3))

print("array a:")
print(a)
print("array b:")
print(b)

array a:
[1 2 3]
array b:
[[9 7 6]
 [5 8 1]
 [3 8 6]]


In [83]:
# adding values to an existing array
a = np.append(a, 4)
a

array([1, 2, 3, 4])

In [84]:
# print the shape and dimension of arrays
print("Shape of a:", np.shape(a))
print("Shape of b:", np.shape(b))

print('Dimension of a:', np.ndim(a))
print('Dimension of b:', np.ndim(b))

Shape of a: (4,)
Shape of b: (3, 3)
Dimension of a: 1
Dimension of b: 2


In [85]:
#  number of elements in the arrays
print('Number of elements in a:', np.size(a))
print('Number of elements in b:', np.size(b))

Number of elements in a: 4
Number of elements in b: 9


### Exercise:  Create a vector with values ranging from 10 to 49
(**hint**: np.arange)

In [86]:
wktest = np.arange(10,50)
print(np.size(wktest))
print(np.shape(wktest))
print(np.ndim(wktest))

40
(40,)
1


### Exercise:  Create a 10x10 array with random values and find the minimum and maximum values
(**hint**: min, max)

In [87]:
arr10_10 = np.random.random((10,10))
print(f"min: {arr10_10.min()}")
print(f"max: {arr10_10.max()}")


min: 0.0004083423332572611
max: 0.9976364748330184


## 4. Indexing

Contents of a NumPy array object can be accessed and modified through indexing. Three types of indexing methods are available − field access, basic slicing and advanced indexing. Here we will explain the first two methods.

##### Tip: notice that numbering of items in an array starts at zero. 

In [88]:
# create an array integer from 1 to 10
X = np.arange(1, 11, dtype=int)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
## FIELD ACCESS
## get a specific item in the array by specifying its index

# get the first item in the array
first = X[0]
# get the fourth item in the array
fourth = X[3]

In [90]:
# EXERCISE: get the seventh item in the array by replacing ___
seventh = X[6]
print(seventh)

7


In [91]:
## BASIC SLICING
## get a slice of the array by defining the start and end index

# get the third until fifth item
X[2:5]

array([3, 4, 5])

In [92]:
## Now lets try for a 2-dimensional array

# first, we create the array
Y= np.arange(1,17).reshape(4,4)
Y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
# use slicing to get the first two rows
Y[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
# use slicing on both rows and columns to get only the last two elements of the first two rows
Y[0:2, 2:4]

array([[3, 4],
       [7, 8]])

### Exercise: use slicing to get the first two elements of the last two rows

In [96]:
Y[2:4, 0:2]

array([[ 9, 10],
       [13, 14]])

## 5. Universal Functions(Ufuncs)

##### tip: press TAB after np. to see list of available ufuncs. np.{TAB}

Allow fast computation in NumPy arrays.

In [99]:
# create an array integer from 1 to 10
X = np.arange(1, 11, dtype=int)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
# find the maximum element of X
np.max(X)

10

In [101]:
# EXERCISE: find the minimum element
np.min(X)

1

In [102]:
# find the mean of values in the X
np.mean(X)

5.5

In [103]:
# get the 4th power of each value
np.power(X, 4)

array([    1,    16,    81,   256,   625,  1296,  2401,  4096,  6561,
       10000])

In [104]:
# get each value to the power 2
np.square(X)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [105]:
# get the square root of each value
np.sqrt(X)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [106]:
# trigonometric functions 
print(np.sin(X))
print(np.tan(X))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]


In [108]:
# calculate more complex functions: item^3 + item^2
np1 = np.power(X, 3) 
np2 = np.square(X)
print(np1)
print(np2)
print(np1 + np2)

[   1    8   27   64  125  216  343  512  729 1000]
[  1   4   9  16  25  36  49  64  81 100]
[   2   12   36   80  150  252  392  576  810 1100]


### Now lets try for a 2-dimensional array

In [109]:
Y= np.arange(1,17).reshape(4,4)
Y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [113]:
# multiply all elements by 2
np.multiply(Y, 2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [48]:
# calculate more complex functions: item^3 + item^2
np.power(Y, 3) + np.square(Y)

array([[   2,   12,   36,   80],
       [ 150,  252,  392,  576],
       [ 810, 1100, 1452, 1872],
       [2366, 2940, 3600, 4352]], dtype=int32)

### Exercise: find the median of values in X


In [115]:
np.median(X)

5.5

### Exercise: create a random vector of size 30 and find the mean value
(**hint**: mean)

In [118]:
rand_vec_30 = np.random.random(30)
np.mean(rand_vec_30)

0.5470285527757308

### Exercise: create a 5x5 matrix with values 1,2,3,4 just below the diagonal
(**hint**: np.diag)

In [120]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 6. Sorting, Comparison and Masking

In [146]:
# create array of 15 elements between 1 and 10
X = np.random.randint(1, 10, 15)
X

array([8, 6, 6, 2, 5, 5, 6, 8, 7, 6, 1, 9, 1, 4, 2])

In [138]:
# create (3,3) size of array elements from 1 and 5
Y = np.random.randint(1,5, (3,3))
Y

array([[3, 3, 2],
       [4, 1, 4],
       [4, 2, 2]])

In [139]:
# sort elements in array X
np.sort(X)

array([1, 1, 1, 2, 2, 2, 4, 5, 5, 6, 6, 7, 7, 9, 9])

In [140]:
# sort the rows
np.sort(Y, axis=0)

array([[3, 1, 2],
       [4, 2, 2],
       [4, 3, 4]])

In [141]:
# sort within the rows
np.sort(Y, axis=1)

array([[2, 3, 3],
       [1, 4, 4],
       [2, 2, 4]])

In [143]:
# perform a true/false comparison test on every element
# == , !=, < , >, >=, <= operations on arrays

# is the element greater than 3?
X > 3

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True, False, False,  True, False, False])

In [145]:
# use masking feature to get the values of comparisons
X[X>3]

array([9, 7, 7, 9, 5, 4, 5, 6, 6])

In [148]:
# more complex masking with multiple conditions
X[(X <= 3) & (X > 1)]

array([2, 2])

### Exercise: given a 1D array, negate all elements which are lower than 28 and higher than 37.

In [149]:
y = np.arange(60)
y[(y >= 28) & (y <= 37)]

array([28, 29, 30, 31, 32, 33, 34, 35, 36, 37])